# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-26 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together=set([('learning_rate', 'layers_count', 'steps_count', 'model')]),
        ),
    ]
